baseURL = 'https://cassiofariasmachado.com/'
languageCode = 'en-us'
title = 'Cássio Farias Machado'
theme = 'typo'

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "Personal website and tech blog created and managed by Cássio Farias Machado"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 10
listSummaries = true
listDateFormat = '2 Jan 2006'

# Footer
showFooter = true
footerContent = """
Coded with ❤️ using [Hugo](https://gohugo.io) and [typo](https://github.com/tomfran/typo) theme
"""

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/cassiofariasmachado"

[[params.social]]
name = "medium"
url = "https://medium.com/@cassiofariasmachado"

[[params.social]]
name = "github"
url = "https://github.com/cassiofariasmachado"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

[[params.menu]]
name = "contact"
url = "/contact"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Deploy settings

[params.giscus]
enable = true
repo = "cassiofariasmachado/website"
repoid = "R_kgDOPjji3A"
category = "Post"
categoryid = "DIC_kwDOPjji3M4CujPi"
mapping = "pathname"
theme = "preferred_color_scheme"

[params.umami]
enable = true
websiteId = "41325d67-f3dd-447f-9f61-aded05b2c17b"
jsLocation = "https://cloud.umami.is/script.js"