# Configure Cloudflare Worker
name = "hosting-cloudflare-worker"
compatibility_date = "2025-07-31"

[build]
command = "./tools/scripts/build.sh"

[assets]
directory = "./public"
not_found_handling = "404-page"